name: Test Updates
on:
  pull_request: {}
  push: {}
jobs:
  updates:
    name: Verify updates
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Check updates
      run: |
        hack/verify-updates.sh
